---
title: "OrientationHist"
author: "Rachel Holman"
date: "2023-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Looking at 3 Years of Survey Data

```{r look at data}
survey21 <- read.csv("2021-06-15-survey.csv", header=TRUE)
survey22 <- read.csv("2022-06-14-survey.csv", header=TRUE)
survey23 <- read.csv("2023-06-13-survey.csv", header=TRUE)

survey21$SurveyYear <- "2021"
survey22$SurveyYear <- "2022"
survey23$SurveyYear <- "2023"

head(survey21)
head(survey22)
head(survey23)

#differing #columns in survey21, differing column headers
```

```{r explore}
hist(survey23$CPU.Number.of.Cores..int.)
hist(survey23$Hard.Drive.Size..in.GB.)
hist(survey23$GPU.CUDA.Number.of.Cores..int.)
hist(survey23$CPU.Cycle.Rate..in.GHz.)
hist(survey23$RAM..in.GB.)
```

```{r compare cpu num of cores over years}
s1 <- hist(survey23$CPU.Number.of.Cores..int.)
s2 <- hist(survey22$CPU.Number.of.Cores..int.)
s3 <- hist(survey21$CPU.Number.of.Cores)

range(c(s1$breaks, s2$breaks, s3$breaks)) # Get range for x-axis
max(c(s1$counts,s2$counts,s3$counts))

par(mfrow=c(3,1))
hist(survey23$CPU.Number.of.Cores..int., xlim = c(-4,16), ylim=c(0,40),
     xlab="2023 Surveys", main="CPU Number of Cores for Computers in the 2023 Cohort")
hist(survey22$CPU.Number.of.Cores..int., xlim = c(-4,16), ylim=c(0,40),
     xlab="2022 Surveys", main="CPU Number of Cores for Computers in the 2022 Cohort")
hist(survey21$CPU.Number.of.Cores, xlim = c(-4,16), ylim=c(0,40),
     xlab="2021 Surveys", main="CPU Number of Cores for Computers in the 2021 Cohort")
```

```{r for fun}
library(scales)
plot(s1, col=alpha("red",0.5), xlim = c(-4,16), ylim=c(0,40))
plot(s2, add=TRUE, col=alpha("blue",0.5))
plot(s3, add=TRUE, col=alpha("yellow",0.5))
```

